sudo: requires
services:
    - docker

before_install:
    - docker build -t andrejschefer/testProjectForCI -f Dockerfile.div .

script:
    -  docker run andrejschefer/testProjectForCI npm run test -- --coverage