sudo: requires
services:
    - docker

before_install:
    - docker build -t andrejschefer/test-project-for-ci -f Dockerfile.div .

script:
    - docker run andrejschefer/test-project-for-ci npm run test -- --coverage