sudo: requires
services:
    - docker

before_install:
    - docker build -t andrejschefer/test-project-for-ci -f Dockerfile.dev .

script:
    - docker run andrejschefer/test-project-for-ci npm run test -- --coverage
    
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env-1" 
    bucket_name: "elasticbeanstalk-us-east-2-038235757971"
    bucket_path: "doker-react2"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"